[project]
name = "eventyay-stripe"
dynamic = ["version"]
description = "Integrates eventyay-stripe with eventyay"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
keywords = ["eventyay"]
authors = [
    {name = "eventyay team", email = "support@eventyay.com"},
]
maintainers = [
    {name = "eventyay team", email = "support@eventyay.com"},
]

dependencies = [
    'stripe==11.3.*',
]

[project.entry-points."pretix.plugin"]
eventyay_stripe = "eventyay_stripe:PretixPluginMeta"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
homepage = "https://github.com/fossasia/eventyay-stripe"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = {attr = "eventyay_stripe.__version__"}

[tool.setuptools.packages.find]
include = ["eventyay*"]
namespaces = false
